[sport]
#0 Soccer
#1 Voleibol
#2 Basket
sport = 1

[server]
servername = www.aztechnologies.tech

[path]
#Windows (Laragon)
path = C:\cursor\aztechnologies\voleibalmetepec
#Linux Development (cPanel)
#path = /home1/aztechn1/public_html/Development/voleibalmetepec
#Linux Production
#path = /home1/aztechn1/public_html/Production/voleibalmetepec

[alias]
#DEV
alias = DEVLMVM
#PROD
#alias = LMVM

[database]
username = aztechn1_lmvmread
password = "(z4%s%Um8[h0"
schema = aztechn1_voleibolmetepec

[database admin]
usernamea = aztechn1_lmvmadm
passworda = "_}xo1OPayw=j"
schemaa = aztechn1_voleibolmetepec

[liga]
liga = Liga Municipal de Voleibol Metepec
adminemail = administrador@voleibolmetepec.com
#website = https://app.voleibolmetepec.com/
website = http://voleibalmetepec.test/

[email]
MAILSMTPDebug = 0
MAILSMTPAuth = true
MAILSMTPSecure = STARTTLS
MAILPort = 587
MAILHost = aztechnologies.tech
MAILUsername = admvoleibolmetepec@aztechnologies.tech
MAILPassword = 'z;mkXu6s{]K4'
MAILSMTPKeepAlive = true
MAILMailer = smtp
MAILsetFrom = admvoleibolmetepec@aztechnologies.tech
MAILaddReplyTo = admvoleibolmetepec@aztechnologies.tech