[sport]
#0 Soccer
#1 Voleibol
#2 Basket
sport = 0

[server]
servername = www.aztechnologies.tech

[path]
#Windows (Laragon)
path = C:\cursor\aztechnologies\huskies
#Linux Development (cPanel)
#path = /home1/aztechn1/public_html/Development/huskies
#Linux Production
#path = /home1/aztechn1/public_html/Production/huskies

[alias]
#DEV
alias = DEVLIDEP6
#PROD
#alias = LIDEP6

[database]
username = aztechn1_lidepread
password = "~CdcyxV01ZTI"
schema = aztechn1_huskies

[database admin]
usernamea = aztechn1_lidepadm
passworda = "-N!NA~bZ;mLt"
schemaa = aztechn1_huskies

[liga]
liga = LIDEP
adminemail = administrador@lidep.com
#website = https://huskies.lidep.net/
website = http://huskies.test/

[email]
MAILSMTPDebug = 0
MAILSMTPAuth = true
MAILSMTPSecure = STARTTLS
MAILPort = 587
MAILHost = aztechnologies.tech
MAILUsername = admhuskies@aztechnologies.tech
MAILPassword = 'l.ml;g5I9(zc'
MAILSMTPKeepAlive = true
MAILMailer = smtp
MAILsetFrom = admhuskies@aztechnologies.tech
MAILaddReplyTo = admhuskies@aztechnologies.tech