[sport]
#0 Soccer
#1 Voleibol
#2 Basket
sport = 0

[server]
servername = www.aztechnologies.tech

[path]
#Windows
path = C:\cursor\aztechnologies\lidep
#Linux
#path = /home1/aztechn1/public_html/Production/lidep

[alias]
#DEV
alias = DEVLIDEP0
#PROD
#alias = LIDEP0

[database]
username = aztechn1_lidepread
password = "~CdcyxV01ZTI"
schema = aztechn1_lidep

[database admin]
usernamea = aztechn1_lidepadm
passworda = "-N!NA~bZ;mLt"
schemaa = aztechn1_lidep

[liga]
liga = LIDEP
adminemail = administrador@lidep.com
#website = https://soccer.lidep.net/
website = https://soccer.test/

[email]
MAILSMTPDebug = 0
MAILSMTPAuth = true
MAILSMTPSecure = STARTTLS
MAILPort = 587
MAILHost = aztechnologies.tech
MAILUsername = admlidep@aztechnologies.tech
MAILPassword = 'kGn7B1Pjz&he'
MAILSMTPKeepAlive = true
MAILMailer = smtp
MAILsetFrom = admlidep@aztechnologies.tech
MAILaddReplyTo = admlidep@aztechnologies.tech