[sport]
#0 Soccer
#1 Voleibol
#2 Basket
sport = 1

[server]
servername = www.aztechnologies.tech

[path]
#Windows (Laragon)
path = C:\cursor\aztechnologies\vollidep
#Linux Development (cPanel)
#path = /home1/aztechn1/public_html/Development/vollidep
#Linux Production
#path = /home1/aztechn1/public_html/Production/vollidep

[alias]
#DEV
alias = DEVLIDEP4
#PROD
#alias = LIDEP4

[database]
username = aztechn1_lidepread
password = "~CdcyxV01ZTI"
schema = aztechn1_vollidep

[database admin]
usernamea = aztechn1_lidepadm
passworda = "-N!NA~bZ;mLt"
schemaa = aztechn1_vollidep

[liga]
liga = VLIDEP
adminemail = administrador@voleibol.lidep.net
#website = https://voleibol.lidep.net/
website = http://vollidep.test/

[email]
MAILSMTPDebug = 0
MAILSMTPAuth = true
MAILSMTPSecure = STARTTLS
MAILPort = 587
MAILHost = aztechnologies.tech
MAILUsername = admvollidep@aztechnologies.tech
MAILPassword = 'n~,PH}oV.i^z'
MAILSMTPKeepAlive = true
MAILMailer = smtp
MAILsetFrom = admvollidep@aztechnologies.tech
MAILaddReplyTo = admvollidep@aztechnologies.tech