[sport]
#0 Soccer
#1 Voleibol
#2 Basket
sport = 0

[server]
servername = www.aztechnologies.tech

[path]
#Windows (Laragon)
path = C:\cursor\aztechnologies\elite
#Linux Development (cPanel)
#path = /home1/aztechn1/public_html/Development/elite
#Linux Production
#path = /home1/aztechn1/public_html/Production/elite

[alias]
#DEV
alias = DEVLIDEP2
#PROD
#alias = LIDEP2

[database]
username = aztechn1_lidepread
password = "~CdcyxV01ZTI"
schema = aztechn1_elite

[database admin]
usernamea = aztechn1_lidepadm
passworda = "-N!NA~bZ;mLt"
schemaa = aztechn1_elite

[liga]
liga = ELITE
adminemail = administrador@elite.lidep.net
#website = https://elite.lidep.net/
website = http://elite.test/

[email]
MAILSMTPDebug = 0
MAILSMTPAuth = true
MAILSMTPSecure = STARTTLS
MAILPort = 587
MAILHost = aztechnologies.tech
MAILUsername = admelite@aztechnologies.tech
MAILPassword = '&2*hr1.C7gaT'
MAILSMTPKeepAlive = true
MAILMailer = smtp
MAILsetFrom = admelite@aztechnologies.tech
MAILaddReplyTo = admelite@aztechnologies.tech